#pragma once
#ifndef _SHARPEN_CPPSTD_HPP
#define _SHARPEN_CPPSTD_HPP

#ifdef _MSVC_LANG
#define SHARPEN_CPP_STANDARD_MACRO _MSVC_LANG
#else
#define SHARPEN_CPP_STANDARD_MACRO __cplusplus
#endif

#if (SHARPEN_CPP_STANDARD_MACRO >= 201103L) && (SHARPEN_CPP_STANDARD_MACRO < 201402L)
#define SHARPEN_CPP_STANDARD 11
#endif

#if (SHARPEN_CPP_STANDARD_MACRO >= 201402L) && (SHARPEN_CPP_STANDARD_MACRO < 201703L)
#define SHARPEN_CPP_STANDARD 14
#endif

#if (SHARPEN_CPP_STANDARD_MACRO >= 201703L) && (SHARPEN_CPP_STANDARD_MACRO < 202002L)
#define SHARPEN_CPP_STANDARD 17
#endif

#if (SHARPEN_CPP_STANDARD_MACRO >= 202002L)
#define SHARPEN_CPP_STANDARD 20
#endif

#undef SHARPEN_CPP_STANDARD_MACRO
#endif